loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: loki-chunks
    type: gcs
write:
  replicas: 3
read:
  replicas: 3
backend:
  replicas: 3

serviceAccount:
  create: true
  name: loki
  annotatate:
    ##
    # With this annotation, we can map a GCP Identity with our K8S service account.l
    iam.gke.io/gcp-service-account: loki@trhyo-ops.iam.gserviceaccount.com

ingress:
  enabled: true
  hosts: ['loki.trhyo.com']
##
# Disable non-used objects
gateway:
  enabled: false
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  metricsInstance:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false