core: "cluster-api:v1.9.6"
infrastructure: "azure:v1.19.2"
addon: "helm:v0.3.1"
enableHelmHook: false
manager:
  featureGates:
    core:
      ClusterTopology: true
additionalDeployments:
  azureserviceoperator-controller-manager:
    deployment:
      containers:
      - name: manager
        args: 
          --crd-pattern: "resources.azure.com/*;containerservice.azure.com/*;keyvault.azure.com/*;managedidentity.azure.com/*;eventhub.azure.com/*;storage.azure.com/*;postgres.database.azure.com/*"

