externalLabels:
    cluster: remote
    prometheus: remote
    prometheus_replica: $(POD_NAME)
  # Enable replicaLabel for deduplication
replicaExternalLabelName: prometheus_replica
prometheusExternalLabelName: prometheus
thanosService:
  enabled: true
prometheusSpec: 
  thanos:
    objectStorageConfig:
      existingSecret:
        name: thanos-config
        key: objstore.yml
  resources:
    # Set appropriate resource constraints
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 250Mi
  storageSpec:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            # Configure the PVC size for the deployment
            storage: 8Gi




thanosService:
  enabled: true
prometheusSpec:
  # Increase replica count
  replicas: 2
  # Configure the object storage for thanos
  thanos:
    objectStorageConfig:
      existingSecret:
        name: thanos-config
        key: objstore.yml