alertmanager:
  enabled: false

compactor:
  enabled: false

distributor:
  replicas: 1

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false

chunks-cache:
  enabled: false

index-cache:
  enabled: false

metadata-cache:
  enabled: false

results-cache:
  enabled: false

minio:
  enabled: false

overrides_exporter:
  replicas: 1

querier:
  replicas: 1

query_frontend:
  replicas: 1

query_scheduler:
  replicas: 1

ruler:
  replicas: 1

store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false

gateway:
  replicas: 1

mimir:
  structuredConfig:
    usage_stats:
      enabled: false
    ingest_storage:
      kafka:
        # Address of Kafka broker to bootstrap the connection
        address: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        # # (optional) SASL credentials provisioned for communications with clients within the cluster
        # sasl_username: "${KAFKA_SASL_USERNAME}" # This is a secret injected via an environment variable
        # sasl_password: "${KAFKA_SASL_PASSWORD}" # This is a secret injected via an environment variable
        # Mimir will auto-create the topic on start up.
        # The topic MUST be provisioned with no fewer partitions than the maximum number of ingester replicas. The value of 1000 here is arbitrarily large to guarantee that.
        topic: mimir-ingest
        auto_create_topic_enabled: true
        auto_create_topic_default_partitions: 1000
    common:
      storage:
        backend: azure
        azure:
          account_key: <your-account-key>
          account_name: staksdemo
          endpoint_suffix: "blob.core.windows.net"

    blocks_storage:
      backend: azure
      azure:
        account_name: staksdemo
        account_key: <your-account-key>
        endpoint_suffix: "blob.core.windows.net"
        container_name: mimir-blocks

    alertmanager_storage:
      backend: azure
      azure:
        account_name: staksdemo
        account_key: <your-account-key>
        endpoint_suffix: "blob.core.windows.net"
        container_name: mimir-alertmanager

    ruler_storage:
      backend: azure
      azure:
        account_name: staksdemo
        account_key: <your-account-key>
        endpoint_suffix: "blob.core.windows.net"
        container_name: mimir-ruler
