grafana:
  enabled: true

alertmanager:
  enabled: true

prometheus:
  externalLabels:
      cluster: primary
      prometheus: primary
      prometheus_replica: $(POD_NAME)
    # Enable replicaLabel for deduplication
  replicaExternalLabelName: prometheus_replica
  prometheusExternalLabelName: prometheus
  thanosService:
    enabled: true
  prometheusSpec:
    additionalArgs:
        - name: storage.tsdb.min-block-duration
          value: 2h
        - name: storage.tsdb.max-block-duration
          value: 2h
        - name: storage.tsdb.retention.time
          value: 2d
        - name: storage.tsdb.path
          value: /prometheus
        - name: web.enable-lifecycle
          value: "true"  
    thanos:
      objectStorageConfig:
        existingSecret:
          name: thanos-config
          key: objstore.yml
    resources:
      # Set appropriate resource constraints
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 250Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              # Configure the PVC size for the deployment
              storage: 8Gi



